version: '3'
services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: job_data
      MYSQL_USER: jobuser
      MYSQL_PASSWORD: jobpassword
    ports:
      - "3306:3306"
    command: "--default-authentication-plugin=mysql_native_password"
    volumes:
      - ./init:/docker-entrypoint-initdb.d/:ro
    networks:
      vpcbr:
        ipv4_address: 10.5.0.5

  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      vpcbr:
        ipv4_address: 10.5.0.6

networks:
  vpcbr:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16
         gateway: 10.5.0.1