version: '3'
services:
  db:
    build:
      context: .
      dockerfile: ./db/Dockerfile
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: job_data
      MYSQL_USER: jobuser
      MYSQL_PASSWORD: jobpassword
    ports:
      - "3306:3306"
    networks:
      vpcbr:
        ipv4_address: 10.5.0.5

  app:
    build:
      context: .
      dockerfile: ./api/Dockerfile
    ports:
      - "8585:8585"
    depends_on:
      - db
    networks:
      vpcbr:
        ipv4_address: 10.5.0.6
    environment:
      DOCKER_CONTAINER: True

networks:
  vpcbr:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16